package catalog;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled Catalog
//  @ File Name : Group.java
//  @ Date : 5/27/2014
//  @ Author :  Buzea Vlad-Calin
//
//




public class Group {
	private String idg;
	private String faculty;
	private int year;
	private String observations;
	public Group(String id,String faculty,int year){
		this.setIdg(id);
		this.setObservations(new String());
		this.setFaculty(faculty);
		this.setYear(year);
	}
	/**
	 * Getter method.
	 * @return the observations
	 */
	public String getObservations() {
		return observations;
	}
	/**Adds new observations to a group.
	 * @param observations the observations to set
	 */
	public void setObservations(String observations) {
		this.observations = observations;
	}
	/**
	 * Getter method.
	 * @return the idg
	 */
	public String getIdg() {
		return idg;
	}
	/**
	 * Setter method.
	 * @param idg the idg to set
	 */
	public void setIdg(String idg) {
		this.idg = idg;
	}
	/**
	 * Returns the information regarding the Group in String format
	 */
	public String toString()
	{
		return idg+" "+faculty+" "+year;
	}
	/**
	 * Getter method.
	 * @return the year
	 */
	public int getYear() {
		return year;
	}
	/**
	 * Setter method.
	 * @param year the year to set
	 */
	public void setYear(int year) {
		this.year = year;
	}
	/**
	 * Getter method.
	 * @return the faculty
	 */
	public String getFaculty() {
		return faculty;
	}
	/**
	 * Setter method.
	 * @param faculty the faculty to set
	 */
	public void setFaculty(String faculty) {
		this.faculty = faculty;
	}
}
