package catalog;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled Catalog
//  @ File Name : Room.java
//  @ Date : 5/27/2014
//  @ Author :  Buzea Vlad-Calin
//
//




public class Room {
	private String idRoom;
	private String address;
	private int capacity;
	public Room(String id,String address){
		this.setIdRoom(id);
		this.setAddress(address);
		capacity=0;
	}
	public Room(String id,String address,int capacity){
		this.setIdRoom(id);
		this.setAddress(address);
		this.capacity=capacity;
	}
	/**
	 * Returns the information of the room in String format.
	 */
	public String toString(){
		String x="\n";
		if(capacity>0)
			x+=idRoom+" ("+capacity+")"+address;
		else
			x+=idRoom+" "+address;
		return x;
	}
	/**
	 * Getter method.
	 * @return the idRoom
	 */
	public String getIdRoom() {
		return idRoom;
	}
	/**
	 * Setter method.
	 * @param idRoom the idRoom to set
	 */
	public void setIdRoom(String idRoom) {
		this.idRoom = idRoom;
	}
	/**
	 * Getter method.
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}
	/**
	 * Setter method.
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}
	/**
	 * Getter method.
	 * @return the capacity
	 */
	public int getCapacity() {
		return capacity;
	}
	/**
	 * Setter method.
	 * @param capacity the capacity to set
	 */
	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}
}
