package catalog;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled Catalog
//  @ File Name : Student.java
//  @ Date : 5/27/2014
//  @ Author :  Buzea Vlad-Calin
//
//




public class Student {
	private String SSID;
	private String firstName;
	private String lastName;
	private String address;
	private Group group;
	
	public Student(String SSID,String firstName,String lastName,String address,Group group){
		this.setSSID(SSID);
		this.setFirstName(firstName);
		this.setLastName(lastName);
		this.setAddress(address);
		this.setGroup(group);
	}

	/**
	 * Getter method.
	 * @return the sSID
	 */
	public String getSSID() {
		return SSID;
	}

	/**
	 * Setter method.
	 * @param sSID the sSID to set
	 */
	public void setSSID(String sSID) {
		SSID = sSID;
	}

	/**
	 * Getter method.
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Setter method.
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Getter method.
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Setter method.
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Getter method.
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Setter method.
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Getter method.
	 * @return the group
	 */
	public Group getGroup() {
		return group;
	}

	/**
	 * Setter method.
	 * @param group the group to set
	 */
	public void setGroup(Group group) {
		this.group = group;
	}
	/**
	 * Returns the information of the Student in String format.
	 */
	public String toString(){
		String x="\n";
		x+=firstName+" "+lastName+" Group: "+group.getIdg();
		return x;
	}
}
